# Generated by Django 4.2 on 2024-03-25 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantuser',
            options={'default_related_name': 'tenant_users'},
        ),
        migrations.AlterModelOptions(
            name='tenantuserinvitation',
            options={'default_related_name': 'tenant_user_invitations', 'verbose_name': 'Tenant User Invitation', 'verbose_name_plural': 'Tenant User Invitations'},
        ),
        migrations.AlterModelOptions(
            name='tenantuserrequest',
            options={'default_related_name': 'tenant_user_requests'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='security_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Security Key'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenantuserinvitation',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenantuserrequest',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
