# Generated by Django 4.2 on 2024-02-02 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vault.folder', verbose_name='Parent Folder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.tenant')),
            ],
            options={
                'verbose_name_plural': 'Folders',
                'permissions': [('create_folder', 'Create Folder'), ('edit_folder', 'Edit Folder'), ('soft_delete_folder', 'Soft Delete Folder'), ('hard_delete_folder', 'Hard Delete Folder')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='VaultItem',
            fields=[
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('password', 'Password'), ('bank_card', 'Bank Card'), ('secured_note', 'Secured Note')], default=None, max_length=12, null=True, verbose_name='Type')),
                ('name', models.CharField(max_length=100)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.folder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.tenant')),
            ],
            options={
                'verbose_name_plural': 'Secured Items',
                'default_related_name': 'secured_items',
            },
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('vaultitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vault.vaultitem')),
                ('card_number', utils.models.SecuredCharField()),
                ('holder_name', utils.models.SecuredCharField()),
                ('expiration_date', utils.models.SecuredCharField()),
                ('cvv', utils.models.SecuredCharField()),
                ('card_type', models.CharField(blank=True, choices=[('master_card', 'Master Card'), ('visa', 'VISA'), ('mada', 'Mada')], default=None, max_length=11, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bank Cards',
            },
            bases=('vault.vaultitem',),
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('vaultitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vault.vaultitem')),
                ('username', utils.models.SecuredCharField()),
                ('password', utils.models.SecuredCharField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Passwords',
            },
            bases=('vault.vaultitem',),
        ),
        migrations.CreateModel(
            name='SecuredNote',
            fields=[
                ('vaultitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vault.vaultitem')),
                ('note', utils.models.SecuredCharField()),
            ],
            options={
                'verbose_name_plural': 'Secured Notes',
            },
            bases=('vault.vaultitem',),
        ),
        migrations.CreateModel(
            name='VaultItemPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.vaultitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaultFolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaultAccessLog',
            fields=[
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, choices=[('access', 'Access'), ('copy_password', 'Copy Password')], default=None, max_length=13, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vault.vaultitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
