# Generated by Django 4.2 on 2024-03-25 07:20

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='LoginItem',
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'default_permissions': [], 'permissions': [('create_folder', 'Create Folder'), ('edit_folder', 'Edit Folder'), ('delete_folder', 'Delete Folder')], 'verbose_name_plural': 'Folders'},
        ),
        migrations.AlterModelOptions(
            name='loginitem',
            options={'verbose_name_plural': 'Login Items'},
        ),
        migrations.AlterModelOptions(
            name='vaultitem',
            options={'default_permissions': [], 'default_related_name': 'secured_items', 'permissions': [('create_vault_item', 'Create Vault Item'), ('edit_vault_item', 'Edit Vault Item'), ('soft_delete_vault_item', 'Soft Delete Vault Item'), ('hard_delete_vault_item', 'Hard Delete Vault Item')], 'verbose_name_plural': 'Secured Items'},
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parent',
        ),
        migrations.AddField(
            model_name='vaultaccesslog',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultaccesslog',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultaccesslog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='folder',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaultaccesslog',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
